tm_core:
  outputs:
    dev:
      account: thrivemarket.us-east-1
      database: DEV_BASE
      role: DEV_GITHUB_ACTION_SA_ROLE
      schema: CI
      threads: 2
      type: snowflake
      user: DEV_GITHUB_ACTION_SA
      password: "kgwhs18$#BAnsdjsu" 
      warehouse: snowball
  
  target: dev
