tm_core:
  outputs:
    dev:
      account: thrivemarket.us-east-1
      database: TM_IGLOO_DEV
      role: DATA_ENGINEERING_TEAM
      schema: CI
      threads: 2
      type: snowflake
      user: DEV_GITHUB_ACTION
      password: "{{ env_var('SNOWFLAKE_SA_PSWD') }}" 
      warehouse: snowball
  
  target: dev
