name: Run dbt
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:  # 1. run when new code is pushed
  schedule: # 2. also run once every day at 8am
   - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: checkout # 3. check out models
      - uses: actions/checkout@v2 
        with: 
          path: dbt

      - name: dbt-run # 4. run dbt
        uses: mwhitaker/dbt-action@master  
        with:
          dbt_command: "dbt run --profiles-dir ." # the actual dbt command!
          dbt_project_folder: "dbt_project"
        env:
          DBT_BIGQUERY_TOKEN: $ # credentials to access this service
