name: Run dbt on PR
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request:
    branches: 
      - main
    types: [opened, reopened]
 
jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    #permissions:
    #  pull-requests: read
    outputs:
      dbt: ${{ steps.changes.outputs.dbt }}
      terraform: ${{ steps.changes.outputs.terraform }}
    steps:
      - name: checkout # 3. check out models
        uses: actions/checkout@v3 
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            dbt:
              - 'dbt/**'
            terraform:
              - 'terraform/**'
  dbt:
    needs: changes
    if: ${{ needs.changes.outputs.dbt == 'true'  }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout # 3. check out models
        uses: actions/checkout@v3
      
      # - name: Get changed files
      #   id: changed-files
      #   uses: tj-actions/changed-files@v41
      #   # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
      #   # with:
      #   #   since_last_remote_commit: true 

      # - name: List all changed files
      #   env:
      #     ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      #   run: |
      #     for file in "$ALL_CHANGED_FILES"; do
      #       echo "$file was changed"
      #     done
          
      # - name: Get changed files in the dbt folder
      #   id: changed-files-specific
      #   uses: tj-actions/changed-files@v41
      #   with:
      #     files: dbt/models/**  # Alternatively using: `docs/**`

      # - name: Run step if any file(s) in the dbt folder change
      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
      #   env:
      #     ALL_CHANGED_FILES: ${{ steps.changed-files-specific.outputs.all_changed_files }}
      #   run: |
      #     echo "One or more files in the docs folder has changed."
      #     echo "List all the files that have changed: $ALL_CHANGED_FILES"
      # - uses: actions/download-artifact@v4
      #   with:
      #     #name: stable-dbt-manifest
      #     path: stable_target
      #     #workflow: dbt-run.yml
      #     #branch: main
      #     #workflow_conclusion: success
      #     #check_artifacts: true
      #     #if_no_artifact_found: fail
      - name: "Download artifact"
        run: |
          WF_NAME="dbt-run.yml"
          ARTIFACT_NAME="stable-dbt-manifest"
          RUN_ID=`gh run list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
          gh run download ${RUN_ID} -n ${ARTIFACT_NAME} -D dbt/stable_dbt_manifest
          # List the artifiact directory/files
          ls -lR
        env:
          GH_TOKEN: ${{ github.token }}
          
      - name: Display structure of downloaded files
        run: ls -R
          
      - name: dbt-run # 4. run dbt
        uses: mwhitaker/dbt-action@master  
        with:
          dbt_command: "dbt run --profiles-dir . --target dev --select state:modified --state stable_dbt_manifest " # the actual dbt command!
          dbt_project_folder: "dbt"
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_SA_PSWD }} # credentials to access this service
          PR_NUMBER: ${{ github.event.number }}


          
